name = "Rust_replication"
uuid = "a893f368-9da3-4b03-9c53-f84480a3d0d3"
authors = ["Franco Diaz Laura <fdiazlau@asu.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
