name = "Rust_replication"
uuid = "a893f368-9da3-4b03-9c53-f84480a3d0d3"
authors = ["Franco Diaz Laura <fdiazlau@asu.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
LinearAlgebra = "1.11.0"
Optim = "1.13.2"
Statistics = "1.11.1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
